plugins {
    id 'java'           // Habilita el soporte para compilar, probar y empaquetar código Java.
    id 'application'    // Permite ejecutar la app directamente desde Gradle y crear distribuciones.
}

group 'com.biblioteca'  // Identificador único de tu organización o proyecto.
version '1.0'  // Versión actual del desarrollo.

repositories {
    mavenCentral()      // Indica a Gradle que descargue las librerías desde el repositorio central de Maven.
}

dependencies {
    /** + INTERFAZ GRÁFICA (Swing con FlatLaf) */
    implementation 'com.formdev:flatlaf:3.0'

    /** + BASE DE DATOS (MySQL) */
    implementation 'mysql:mysql-connector-java:8.0.33'
    implementation 'com.zaxxer:HikariCP:5.0.1' //Pool de conexiones para mejorar el rendimiento al acceder a la base de datos.

    // Recomendado: SLF4J para logs de Hikari
    implementation 'org.slf4j:slf4j-simple:2.0.12'

    /** + SEGURIDAD (BCrypt) */
    implementation 'org.mindrot:jbcrypt:0.4'

    /** + LOMBOK (Productividad) */
    compileOnly 'org.projectlombok:lombok:1.18.28'
    annotationProcessor 'org.projectlombok:lombok:1.18.28'

    /** + LOGGING (Registro de eventos) */
    implementation 'org.slf4j:slf4j-api:2.0.7'
    implementation 'org.slf4j:slf4j-simple:2.0.7'

    /** + REPORTES */
    implementation 'com.itextpdf:itext7-core:7.2.5'

    // JPA / HIBERNATE: Para mapear tus clases a la base de datos
    // Es la implementación que entiende las anotaciones @Entity y @Table
    implementation 'org.hibernate.orm:hibernate-core:6.4.1.Final'

    // 1. La API de Validación (Define las anotaciones como @NotNull, @NotBlank)
    implementation 'jakarta.validation:jakarta.validation-api:3.0.2'

    // 2. La Implementación de Referencia (Hibernate Validator)
    // La API sola es solo un contrato; esta librería es la que "hace el trabajo" de validar.
    implementation 'org.hibernate.validator:hibernate-validator:8.0.1.Final'
}

application {
    // Define cuál es la clase que contiene el método public static void main(String[] args)
    mainClass = 'com.biblioteca.Main'
}